### ISSUE TITLE
Keep all HTML in your views

### ISSUE THREAD

**Issue by thiagooak** [abarretti/SantaMonicaMovieRentalsSILEX#4]
https://github.com/abarretti/SantaMonicaMovieRentalsSILEX/blob/fe851806f7a8c264c8dc044a22669255cbdba11e/app/SMMRSite/Models/InventoryModels/inventoryDAOClass.php#L34

**Comment by abarretti** [comment]
There is a crazy amount of HTML in my DAO classes. This will take some time...

**Comment by abarretti** [comment]
I'm making progress with this. I have to redo a lot of code. I'm hoping to generate a pull request and have all the issues corrected by Sunday. Then I'll eventually need to clean up the code with better patterns (for loops instead of a bunch of conditionals)

Also, I am realizing now that I should have created separate classes for each responsibility. Ex. Instead of 1 Booking Class that handles both Booking Creations and Booking Returns, I should have made 2 classes that were responsible for each. Single Responsibility in SOLID ;-) I probably won't redo the code but just know I am aware of it :)
