### ISSUE TITLE
Make file names case sensitive

### ISSUE THREAD

**Issue by thiagooak** [abarretti/SantaMonicaMovieRentalsSILEX#8]
From  http://www.php-fig.org/psr/psr-4/ `http://www.php-fig.org/psr/psr-4/`

You have many files starting with a lower case but having the class name starting with upper case

e.g. `InventoryDAOClass` file name is `inventoryDAOClass.php` but should be `InventoryDAOClass.php`

this will not matter on Windows but does matter on Linux.

You can also drop the `Class` suffix on your classes

**Comment by abarretti** [comment]
Fixed. Although I didn't drop the Class suffixes because they are passed as arguments in a lot of functions. I'm worried I'll forget one and cause an error. But I have noted to not include the Class suffix going forward :)

Should I also capitalize the first letter of the twig views? Or does this only apply to the php files in the app?
